/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package help4travelling;

/**
 *
 * @author Agustin
 */
public class ConexionBD extends javax.swing.JPanel {

    /**
     * Creates new form ConexionBD
     */
    public ConexionBD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lbl_menu = new javax.swing.JLabel();
        lbl_mostrar_registros = new javax.swing.JLabel();
        lbl_mostrar_registros1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_mostrar_registros2 = new javax.swing.JLabel();
        txt_conectarBD = new javax.swing.JTextField();
        btn_conectarBD = new javax.swing.JLabel();
        btn_salirBD = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/Help4Travelling-logo.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setIconTextGap(8);

        lbl_menu.setBackground(new java.awt.Color(1, 82, 160));
        lbl_menu.setFont(new java.awt.Font("FreeSans", 0, 36)); // NOI18N
        lbl_menu.setForeground(java.awt.Color.white);
        lbl_menu.setText("                                           ");
        lbl_menu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbl_menu.setOpaque(true);

        lbl_mostrar_registros.setBackground(java.awt.Color.darkGray);
        lbl_mostrar_registros.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N
        lbl_mostrar_registros.setForeground(new java.awt.Color(254, 254, 254));
        lbl_mostrar_registros.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_mostrar_registros.setText("Registros   ");
        lbl_mostrar_registros.setName("lbl_mostrar_registros"); // NOI18N
        lbl_mostrar_registros.setOpaque(true);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lbl_mostrar_registros1.setBackground(new java.awt.Color(25, 25, 25));
        lbl_mostrar_registros1.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        lbl_mostrar_registros1.setForeground(new java.awt.Color(254, 254, 254));
        lbl_mostrar_registros1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_mostrar_registros1.setFocusable(false);
        lbl_mostrar_registros1.setName("lbl_mostrar_registros"); // NOI18N
        lbl_mostrar_registros1.setOpaque(true);
        add(lbl_mostrar_registros1);
        lbl_mostrar_registros1.setBounds(0, 207, 650, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/Help4Travelling-logo.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setFocusable(false);
        jLabel4.setIconTextGap(8);
        add(jLabel4);
        jLabel4.setBounds(290, 40, 78, 77);

        lbl_mostrar_registros2.setBackground(new java.awt.Color(1, 82, 158));
        lbl_mostrar_registros2.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        lbl_mostrar_registros2.setForeground(new java.awt.Color(254, 254, 254));
        lbl_mostrar_registros2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_mostrar_registros2.setText("CONECTAR CON BASE DE DATOS");
        lbl_mostrar_registros2.setFocusable(false);
        lbl_mostrar_registros2.setName("lbl_mostrar_registros"); // NOI18N
        lbl_mostrar_registros2.setOpaque(true);
        add(lbl_mostrar_registros2);
        lbl_mostrar_registros2.setBounds(0, 0, 660, 30);

        txt_conectarBD.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        txt_conectarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_conectarBDActionPerformed(evt);
            }
        });
        add(txt_conectarBD);
        txt_conectarBD.setBounds(220, 150, 220, 30);

        btn_conectarBD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_conectarBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/right-arrow.png"))); // NOI18N
        btn_conectarBD.setText("jLabel2");
        btn_conectarBD.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(btn_conectarBD);
        btn_conectarBD.setBounds(610, 169, 38, 38);

        btn_salirBD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_salirBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help4travelling/img/error.png"))); // NOI18N
        btn_salirBD.setText("jLabel2");
        btn_salirBD.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_salirBD.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(btn_salirBD);
        btn_salirBD.setBounds(3, 169, 37, 37);

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel5.setText("Direccion IP:");
        jLabel5.setFocusable(false);
        add(jLabel5);
        jLabel5.setBounds(280, 120, 100, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_conectarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_conectarBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_conectarBDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_conectarBD;
    private javax.swing.JLabel btn_salirBD;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_menu;
    private javax.swing.JLabel lbl_mostrar_registros;
    private javax.swing.JLabel lbl_mostrar_registros1;
    private javax.swing.JLabel lbl_mostrar_registros2;
    private javax.swing.JTextField txt_conectarBD;
    // End of variables declaration//GEN-END:variables
}
